Меняй-удаляй (часть 1)
htmlacademy-ecmascript/1489861-cinemaddict-14 pull request #12
Opened 2021-05-11 10:16 UTC by El-Leto

---
:mortar_board: [Меняй-удаляй (часть 1)](https://up.htmlacademy.ru/ecmascript/14/user/1489861/tasks/12)

:boom: https://htmlacademy-ecmascript.github.io/1489861-cinemaddict-14/12/

2021-05-11 12:49 UTC, AlexMasterov requested changes

2021-05-11 12:49 UTC, AlexMasterov commented on src/presenter/films-list.js
> +        return filtredFilms.sort((filmA, filmB) => {return filmB.date - filmA.date;});
<details>
<summary>presenter/films-list.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/47bebb30fe4f8084ba5718a7426a2a3b0b2018f7/src/presenter/films-list.js#L53
</details>

```diff
- return filtredFilms.sort((filmA, filmB) => {return filmB.date - filmA.date;});
+ return filtredFilms.sort((filmA, filmB) => filmB.date - filmA.date);
```

<details>
<summary>presenter/films-list.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/47bebb30fe4f8084ba5718a7426a2a3b0b2018f7/src/presenter/films-list.js#L55
</details>

Нужно также упростить самостоятельно.

2021-05-11 12:49 UTC, AlexMasterov commented on src/presenter/films-list.js
> +    if (resetRenderedFilmCount) {
<details>
<summary>presenter/films-list.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/47bebb30fe4f8084ba5718a7426a2a3b0b2018f7/src/presenter/films-list.js#L163-L167
</details>

[`Д 14`](https://up.htmlacademy.ru/ecmascript/14/criteries#d14)
> Там, где возможно, в присвоении значения вместо `if` используется тернарный оператор

2021-05-11 12:49 UTC, AlexMasterov commented on src/presenter/films-list.js
>  export default class FilmList {
presenter/`films-list`.js !== `FilmList`

[`Б 27`](https://up.htmlacademy.ru/ecmascript/14/criteries#b27)
> Имя модуля должно соответствовать его содержимому

> Например, если в модуле лежит класс `GameView`, то и имя модуля должно быть `game-view`.js

2021-05-11 12:49 UTC, AlexMasterov commented on src/presenter/films-list.js
>    _handleShowMoreButtonClick() {
<details>
<summary>_handleShowMoreButtonClick</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/47bebb30fe4f8084ba5718a7426a2a3b0b2018f7/src/presenter/films-list.js#L105
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/47bebb30fe4f8084ba5718a7426a2a3b0b2018f7/src/presenter/films-list.js#L107
</details>

**2x** `this._getFilms()`

2021-05-11 12:49 UTC, AlexMasterov commented on src/presenter/films-list.js
> +    if (this._getFilms().length === 0) {
<details>
<summary>_renderFilmsBoard</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/47bebb30fe4f8084ba5718a7426a2a3b0b2018f7/src/presenter/films-list.js#L130-L133
</details>

const films = this.`_getFilms()`;
const filmCount = films.`length`;

if (this.`_getFilms()`.`length` === 0) {

🤔

<details>
<summary>Покажи, что лучше сделать</summary>

Вместо этого реализуй метод модели:

```diff
- if (this._getFilms().length === 0) {
+ if (this._filmsModel.isEmpty()) {
```
</details>

2021-05-11 12:49 UTC, AlexMasterov commented on src/presenter/films-list.js
> +      this._renderedFilmCount = Math.min(filmCount, this._renderedFilmCount);
<details>
<summary>_clearFilmsBoard</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/47bebb30fe4f8084ba5718a7426a2a3b0b2018f7/src/presenter/films-list.js#L153
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/47bebb30fe4f8084ba5718a7426a2a3b0b2018f7/src/presenter/films-list.js#L166
</details>

`filmCount` используется только в случае выполнения условия.

2021-05-11 12:54 UTC, AlexMasterov commented on src/view/main-navigation.js
> +const createMainNavigationItemTemplate = (filter, currentFilterType) => {
См. [`ТЗ 3`](https://up.htmlacademy.ru/ecmascript/14/project/cinemaddict#other):
> В зависимости от состояния, некоторым элементам управления применяются соответствующие классы оформления. Например, активный фильтр и т. д.  Примеры доступны в директории с вёрсткой (`markup`)

<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/117818168-06333580-b271-11eb-9206-dfc91f248e5c.png)
</details>

Сейчас при выборе фильтра активным (по разметке) всегда становится `Favorites`.

Нужно разобраться и исправить.

2021-05-11 13:01 UTC, AlexMasterov commented on src/presenter/films-list.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/117819200-fbc56b80-b271-11eb-86a5-64f1a36c4cd9.png)

</details>

Например, если отфильтровать список по `Favorites` (или `Watchlist`, `History`), потом открыть попап, и в нём убрать отмету `Add to favorites`, то карточку нужно удалить из списка, а попап оставить открытым.

Сейчас после отметки кнопок попап закрывается.

Нужно доработать.

2021-05-11 13:04 UTC, AlexMasterov requested changes

2021-05-11 13:04 UTC, AlexMasterov commented on src/presenter/films-list.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/117819704-7bebd100-b272-11eb-9371-9911154757cc.png)

</details>

При выборе фильтра `All movies` рендерится пустой список.

Нужно исправить.

2021-05-11 13:17 UTC, AlexMasterov requested changes

2021-05-11 13:17 UTC, AlexMasterov commented on src/presenter/films-list.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/117821307-1ef11a80-b274-11eb-8a72-d5463f2bc0e8.png)

</details>

Если в попапке выбрать эмоцию, то перестает работать _синхронная_ отметка кнопок на добавление/удаление в избранное и т.п.

Нужно разобраться и исправить.

2021-05-13 18:28 UTC, AlexMasterov requested changes
Нужно еще немного доработать.

2021-05-13 18:29 UTC, AlexMasterov commented on src/presenter/films-list.js
Замечание актуально.

Если в попапе убрать отмету `Add to favorites` (или `Watchlist`, `History`), то карточку нужно удалить из списка, а её попап не закрывать.

> Это ответ текущих авторов курса, который мы обсуждали в чате

2021-05-13 18:55 UTC, AlexMasterov requested changes

2021-05-13 18:55 UTC, AlexMasterov commented on src/presenter/film-card.js
<details>
<summary>presenter/film-card.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/06f2c6046ec66b01ce5d3fd83aa7a6a0013f6ede/src/presenter/film-card.js#L69-L70
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/06f2c6046ec66b01ce5d3fd83aa7a6a0013f6ede/src/presenter/film-card.js#L100-L101
</details>

Вызов `remove(this._popupView)` повторяется в `this._closeFilmDetail`.

2021-05-13 19:00 UTC, AlexMasterov requested changes

2021-05-13 19:00 UTC, AlexMasterov commented on src/main.js
Если открыть попап и на её карточке в списке отметить любую кнопку, то он закрывается.

2021-05-13 19:04 UTC, AlexMasterov requested changes

2021-05-13 19:04 UTC, AlexMasterov commented on src/presenter/films-list.js
> +    const filmsList = films.slice(this._renderedFilmCount, newRenderedFilmCount);
```js
Array.isArray(filmsList) // true
```
Б8

2021-05-13 22:12 UTC, AlexMasterov requested changes

2021-05-13 22:12 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/118193224-063d5c00-b450-11eb-9156-c6e39ddc285e.png)

</details>

Если применить фильтр `Watchlist` и открыть попап у карточке из отфильтрованного списка, то снятие отметки `Add to watchlist` удалит карточку из списка, но при повторной отметки она не вернётся в список.

Буду уточнять у текущих авторов, насколько это важно для ТЗ.

2021-05-13 22:12 UTC, AlexMasterov commented on src/main.js
См. ТЗ:
> Одновременно может быть открыт только один попап. При открытии нового попапа прежний закрывается, например при клике на другую карточку при открытом попапе

<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/118193640-b4e19c80-b450-11eb-9abb-7cee12455dbc.png)
![image](https://user-images.githubusercontent.com/700213/118193877-1b66ba80-b451-11eb-8027-1381272544e6.png)

</details>

Если открыть попап с списке с фильтром `All movies`, а потом применить другой фильтр (где будет эта карточка) и снова открыть её попап, то их станет _два_.

<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/118193982-48b36880-b451-11eb-94a1-9c29a23a81c6.png)
</details>

Если применить сортировку и снова открыть попап, то их станет _три_. 

> Думаю, что можно сделать больше и повесить страницу по памяти 😃

2021-05-13 23:34 UTC, AlexMasterov requested changes

2021-05-13 23:34 UTC, AlexMasterov commented on src/main.js
См. ТЗ:
> В случае отсутствия фильмов вместо списка отображается текст: «There are no movies in our database».

<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/118199755-74881b80-b45c-11eb-8677-429c2d1eca30.png)

</details>

<details>
<summary>Ожидание</summary>

![image](https://user-images.githubusercontent.com/700213/118199917-c0d35b80-b45c-11eb-8dc4-3cef8fb4c170.png)

</details>

> Сломалось!

См. также [ответ текущих авторов курса](https://up.htmlacademy.ru/ecmascript/14/module/7/questions#:~:text=%D0%94%D0%B0%2C%20%D1%8D%D1%82%D0%BE%20%D0%BE%D1%82%D0%BD%D0%BE%D1%81%D0%B8%D1%82%D1%81%D1%8F%20%D0%B8%20%D0%BA%20%22%D0%BF%D1%83%D1%81%D1%82%D1%8B%D0%BC%22%20%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0%D0%BC%20%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D0%BE%D0%B2%20%D0%BF%D0%BE%20%D0%BA%D0%BE%D0%BD%D0%BA%D1%80%D0%B5%D1%82%D0%BD%D0%BE%D0%BC%D1%83%20%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D1%83.):
> Да, это относится и к "пустым" спискам фильмов по конкретному фильтру

Нужно доработать.

2021-05-14 02:48 UTC, AlexMasterov requested changes

2021-05-14 02:48 UTC, AlexMasterov commented on src/presenter/films-list.js
> +    this._renderedFilmCount = resetRenderedFilmCount ? FILM_COUNT_PER_STEP : Math.min(this._get().length, this._renderedFilmCount);
```js
const films = [{}]; // .length (1)

Math.min(films.length, this._renderedFilmCount) // 1
```
Если в модели меньше `5`-и фильмов, то здесь для последующего рендера можно получить неправильное значение `this._renderedFilmCount`. Карточка вернётся в отфильтрованный список, но будет скрыта за кнопкой `Show More`.

<details>
<summary>Проблема наглядно</summary>

![image](https://user-images.githubusercontent.com/700213/118213990-ac508c80-b477-11eb-9a75-75c82aacbfb5.png)
</details>

Возможное решение:
```js
this._renderedFilmCount = resetRenderedFilmCount 
  ? FILM_COUNT_PER_STEP 
  : Math.min(films.length + FILM_COUNT_PER_STEP, this._renderedFilmCount);
```

> На проверке при условии что фильмов всегда `20` такое воспроизвести (и даже указать) не получится, но это баг :)

2021-05-14 14:12 UTC, AlexMasterov requested changes

2021-05-14 23:23 UTC, AlexMasterov commented on src/presenter/films-list.js
>    _render() {
<details>
<summary>presenter/films-list.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/5a456f58477f75e74fd954e51de5796134da37ce/src/presenter/films-list.js#L130
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/5a456f58477f75e74fd954e51de5796134da37ce/src/presenter/films-list.js#L147
</details>

Советую вынести в начало метода `FilmsList.init` и рендерить _один_ раз в любом случае.

<details>
<summary>presenter/films-list.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/5a456f58477f75e74fd954e51de5796134da37ce/src/presenter/films-list.js#L129-L133
</details>

Советую вынести это условие в метод `FilmsList.init`.

2021-05-14 23:35 UTC, AlexMasterov commented on src/presenter/films-list.js
>      this._filmCardPresenter = {};
<details>
<summary>Покажи, что опять можно улучшить</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/5a456f58477f75e74fd954e51de5796134da37ce/src/presenter/films-list.js#L33

Советую для хранения презентеров вместо объекта попробовать использовать [`Map`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Map).

> Текущие авторы курса (с подачи наставников) давно приняли решение использовать `Map`, но в сам курс и демо проект он будет добавлен только в след. интенсиве

Для замены достаточно освоить след. методы:

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/5a456f58477f75e74fd954e51de5796134da37ce/src/presenter/films-list.js#L62-L64
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/5a456f58477f75e74fd954e51de5796134da37ce/src/presenter/films-list.js#L157-L159

См. [Map.p.`forEach`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Map/forEach).

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/5a456f58477f75e74fd954e51de5796134da37ce/src/presenter/films-list.js#L71

См. [Map.p.`set`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Map/set).

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/5a456f58477f75e74fd954e51de5796134da37ce/src/presenter/films-list.js#L192

См. [Map.p.`get`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Map/get).

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/5a456f58477f75e74fd954e51de5796134da37ce/src/presenter/films-list.js#L160

См. [Map.p.`clear`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Map/clear).

См. также [Map.p.`size`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Map/size).
</details>

2021-05-15 17:20 UTC, El-Leto commented on src/presenter/films-list.js
>    _render() {
Там была проблема с рендером сортировки. Она должна идти до this._mainContentView, и когда сразу в init рендерился этот контейнер, то потом при рендере сортировки, она всегда была после (уже после showmore)

2021-05-17 18:47 UTC, AlexMasterov commented
👍🏻

GitHub открыл загрузку видео для всех пользователей. На память о задание оставлю пару кубов 😃

> Баг в коде: [coub.com/view/14l10r](https://coub.com/view/14l10r)

https://user-images.githubusercontent.com/700213/118495375-d0d48f00-b72b-11eb-9672-fafebb90ad9f.mp4

> [coub.com/view/2d273l](https://coub.com/view/2d273l)

https://user-images.githubusercontent.com/700213/118495086-8226f500-b72b-11eb-81fe-fd17a6924fe4.mp4

>  [coub.com/view/2qog6m](https://coub.com/view/2qog6m)

https://user-images.githubusercontent.com/700213/118495571-fbbee300-b72b-11eb-836d-a613b44912b0.mp4

2021-05-17 18:48 UTC, merged

2021-05-17 18:50 UTC, El-Leto commented
Над первым в голос смеялась!)