Module7 task2
htmlacademy-ecmascript/1489861-cinemaddict-14 pull request #13
Opened 2021-05-20 07:45 UTC by El-Leto

2021-05-20 07:49 UTC, El-Leto commented
Пока не верно работает выбор активной кнопки в меню. Буду сейчас еще разбираться. В статистике при фильтрах по дням, месяц пишет 0. Но это верно, потому что я в моковых данных  вставила функцию на дату просмотра такую же, как на создание фильмов. Соответственно они все были просмотрены больше года назад, поэтому появляются только на всех фильмах.

2021-05-20 11:46 UTC, AlexMasterov requested changes
Нужно постараться минимизировать кол. циклов и в оставшихся не делать странного.

2021-05-20 11:46 UTC, AlexMasterov commented on src/view/stats.js
> +
<details>
<summary>view/stats.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/view/stats.js#L34
</details>

if (`!films.length`) { ... }

<details>
<summary>view/stats.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/view/stats.js#L39
</details>

`countFilmsByGenre.length ?`

<details>
<summary>view/stats.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/view/stats.js#L30
</details>

`sortedFilmByGenreCounts ?`

Здесь проверяется наличие значения в переменной или само значение?

Желательно сделать _явную_ проверку на кол. с числом, которая лучше для понимание кода и не требует включения неявного приведения типов.

> См. также [руководство по написанию JavaScript-кода от Airbnb](https://github.com/leonidlebedev/javascript-airbnb#comparison--shortcuts)

2021-05-20 11:46 UTC, AlexMasterov commented on src/view/stats.js
> +  const countFilmsByGenre = getSortedfFilms(films);
```js
typeof countFilmsByGenre === 'function' // false
```

`count`FilmsByGenre

Это не функция.

[`Б 4`](https://up.htmlacademy.ru/ecmascript/14/criteries#b4)
> Для названия значений используются английские **существительные**

```js
Array.isArray(countFilmsByGenre) // true
```
Это _массив_.

[`Б 8`](https://up.htmlacademy.ru/ecmascript/14/criteries#b8)
> Массивы названы существительными во множественном числе

2021-05-20 11:46 UTC, AlexMasterov commented on src/view/stats.js
> +const getSortedfFilms = (films) => {
<details>
<summary>getSortedfFilms</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/view/stats.js#L19-L21
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/view/stats.js#L23-L27
</details>

В каждом случае для наполнения данными создается _новый_ массив и объект.

Зачем на каждой итерации создать их заново 🤔

У меня нет слов, см. [критику от стороннего человека](https://www.youtube.com/watch?v=4rYIfpon5i4#t=31m27s).

2021-05-20 11:46 UTC, AlexMasterov commented on src/view/stats.js
> +    return (typeof acc[rec] !== 'undefined')
`(`typeof acc[rec] !== 'undefined'`)`

Здесь скобки `()` не нужны — визуальный мусор.

`typeof` acc[rec] !== 'undefined'

Проверить значение переменной на `undefined` можно без `typeof`. Цикл и так медленный! 😃

2021-05-20 11:46 UTC, AlexMasterov commented on src/main.js
Блок с кнопками управления не работает.

Нужно разобраться и исправить.

2021-05-20 11:46 UTC, AlexMasterov commented on src/main.js
Для карточке не открывает попап, а в консоли ошибка:
```
table.js:30 Uncaught TypeError: Cannot read property 'length' of undefined
```
Б2

Нужно исправить.

2021-05-20 11:46 UTC, AlexMasterov commented on src/main.js
См. ТЗ:

> Звание зависит от количества просмотренных фильмов

> `0` — блок со званием не отображается

После исправления кнопок нужно проверить этот пункт ТЗ.

2021-05-20 11:46 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/118972297-133edb80-b979-11eb-8f5f-a1c0f69dd214.png)

</details>

Компонент статистики и объект `Chart` избыточно создается и рендерится без переключения на страницу `Stats` (и не удаляется после переключения со страницы `Stats`) 😟

2021-05-20 11:46 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/118972953-d1626500-b979-11eb-88e1-33735ddc6ef7.png)

</details>

При выборе страницы `Stats` активной остается `All movies`.

См. ТЗ 3.

Нужно исправить.

2021-05-21 04:48 UTC, AlexMasterov requested changes

2021-05-21 04:48 UTC, AlexMasterov commented on src/main.js
См. ТЗ:
> Звание зависит от количества просмотренных фильмов, вычисляется при загрузке приложения и м**ожет изменяться в ходе использования пользователем приложения (при добавлении или удалении фильмов из просмотренных)**

После исправления кнопок нужно проверить этот пункт ТЗ.

2021-05-21 04:48 UTC, AlexMasterov commented on src/main.js
Добавление фильма в просмотренные (и его удаление) должно учитываться в статистике.

После исправления кнопок это нужно проверить.

2021-05-21 09:26 UTC, AlexMasterov requested changes

2021-05-21 09:26 UTC, AlexMasterov commented on src/view/stats.js
> +  const watchedMoviesCount = watchedFilms.length;
<details>
<summary>utils/statistics.js (getRankName)</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/utils/statistics.js#L11-L12
</details>

<details>
<summary>view/stats.js (getSortedfFilms)</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/view/stats.js#L17
</details>

<details>
<summary>view/stats.js (createStatsTemplate)</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/view/stats.js#L118-L119
</details>

Места _повторного_ вычисления `watchedFilms` и `watchedMoviesCount` (= `watchedFilms.length`).

<details>
<summary>view/stats.js (getTopGenre)</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/view/stats.js#L38
</details>

<details>
<summary>view/stats.js (renderChart)</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/view/stats.js#L38
</details>

Места _повторного_ получения сортированного массива.

Всё повторяется в одном месте и результат работы функций никак не переиспользуется, словно код между собой не связан. Причем почти каждая функция пытается сделать всё сама по новой.

2021-05-21 09:35 UTC, AlexMasterov commented on src/view/stats.js
> +const createStatsTemplate = ({films, range}, filteredMovies) => {
Нашел еще одно странное место:

<details>
<summary>view/stats.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/view/stats.js#L118-L119
</details>

const watched`Films` = filtered`Movies`.filter((film) =&gt; film.userDetails.isWatched);  
const watched`Movies`Count = watched`Films`.length;

2021-05-21 09:59 UTC, AlexMasterov commented on src/utils/statistics.js
> +  const [rankName] = Object.entries(rank)
<details>
<summary>utils/statistics.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/utils/statistics.js#L4-L8
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/utils/statistics.js#L13
</details>

Объект `rank` не изменяется, а значит применение `Object.entries(rank)` всегда возвращает один и тот же результат.

[`Д 19`](https://up.htmlacademy.ru/ecmascript/14/criteries#d19)
> Массивы и объекты, содержимое которых вычисляется, **собираются один раз, а после этого только переиспользуются**

2021-05-21 10:06 UTC, AlexMasterov commented on src/utils/statistics.js
> +    return films;
<details>
<summary>filterWatchedFilmsInRange</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/utils/statistics.js#L20
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/utils/statistics.js#L22
</details>

Функция с названием `filter`WatchedFilmsInRange может вернуть ссылку на _прежний_ массив.

См. [замечание с объяснением из прошлого ревью](https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/pull/12#discussion_r630061316).

2021-05-21 10:10 UTC, AlexMasterov commented on src/view/stats.js
> +  const sortedFilmByGenreCounts = Object.entries(filmsByGenreCounts).map(([ key, val ]) => ({ key, counts: val })).sort((a, b) => b.counts - a.counts);
({ key, `counts`: val })).sort((a, b) => b.`counts` - a.`counts`);

`counts` почему то во множ. числе.

2021-05-21 10:39 UTC, AlexMasterov commented on src/utils/statistics.js
> +const getRankName = (films) => {
<details>
<summary>getRankName</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/utils/statistics.js#L10-L18
</details>

Сравнил это решение с тем, что вообще не использует массив для вычисления звания, но также включил в него вычисление кол. просмотренных фильмов, хотя это должно происходит за пределами функции.

```
getProfileTitle x 5,988,629 ops/sec ±0.31% (22 runs sampled)
getRankName     x 623,338   ops/sec ±0.34% (22 runs sampled)
```
В итоге `getRankName` работает почти в **10** раз медленнее условно эталонного решения.

<details>
<summary>getRankName Runtime</summary>

```
                      Runtime Function/C++ Builtin        Time             Count
========================================================================================
                                      JS_Execution    568.41ms  38.12%      2124   0.05%
                                     ObjectEntries    239.57ms  16.07%    580149  13.38%
                                CreateDataProperty    198.29ms  13.30%   1160298  26.75%
                                       GetProperty    119.16ms   7.99%   1740487  40.13%
                           ArraySpeciesConstructor     21.78ms   1.46%    580149  13.38%
                              ParseFunctionLiteral     16.78ms   1.13%      2370   0.05%
                             GC_SCAVENGER_SCAVENGE     15.57ms   1.04%       429   0.01%
```
</details>

`ObjectEntries` и создание промежуточных массивов, а потом их удаление сборщиком мусора (= `GC_SCAVENGER_SCAVENGE`) занимает почти половину времени работы функции.

2021-05-21 11:39 UTC, AlexMasterov requested changes

2021-05-21 11:39 UTC, AlexMasterov commented on src/view/stats.js
> +const getSortedfFilms = (films) => {
getSorted`f`Films

Опечатка.

[`Б 4`](https://up.htmlacademy.ru/ecmascript/14/criteries#b4)
> Для названия значений используются **английские существительные**

2021-05-21 12:11 UTC, AlexMasterov commented on src/view/stats.js
> +  const minutes = Math.floor(totalWatchedTimeInMin) - (hours * 60);
<details>
<summary>getTimeFromMins</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/utils/format-date.js#L10-L18
</details>

<details>
<summary>view/stats.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/view/stats.js#L121-L122
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/c735773b888c9454606fbc199f05faa9ff8b64c8/src/view/stats.js#L159
</details>

Можно попробовать переиспользовать.

Если не изменять функцию `getTimeFromMins`, то можно с помощью `String.p.replace` заменить в её выводе `h` на `<span class="statistic__item-description">h</span>` и т.п.

2021-05-22 05:34 UTC, AlexMasterov requested changes
К обеду постараюсь дописать остальные замечания и ответить в чате.

2021-05-22 05:34 UTC, AlexMasterov commented on src/utils/statistics.js
> +const getRankName = (films) => {
<details>
<summary>getRankName</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/0ef23aac0abab98a57c24529e784cf0b52089cf5/src/utils/statistics.js#L21-L25
</details>

```js
getRankName(0) // Novice
```
См. https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/pull/13#discussion_r636019809.

Желательно это предусмотреть в самой функции.

<details>
<summary>Покажи класс</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/0ef23aac0abab98a57c24529e784cf0b52089cf5/src/utils/statistics.js#L15-L19

Можно отсортировать звания в обратном порядке: (от большего к меньшему)
```js
const WATCHED_TITLES = [
  {watched: 21, title: 'Movie Buff'},
  {watched: 11, title: 'Fan'},
  {watched: 1, title: 'Novice'},
];
```
> Отсортировать можно вручную или с помощью кода

Тогда проверку можно записать так:
```js
const getRankTitle = (value) => value > 0
  ? WATCHED_TITLES.find(({watched}) => watched <= value).title
  : '';
```
```js
const getRankTitle = (value) => WATCHED_TITLES 
  .find(({watched}) => watched <= value)
  .title || '';
```
Также "пустое" звания можно добавить прямо в `WATCHED_TITLES`:
```js
{ watched: 0, title: '' },
```
</details>

2021-05-22 05:34 UTC, AlexMasterov commented on src/utils/statistics.js
> +  { title: 'Movie Buff', watched: Infinity},
<details>
<summary>utils/statistics.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/0ef23aac0abab98a57c24529e784cf0b52089cf5/src/utils/statistics.js#L16-L18
</details>

`Infinity` 🤔

```js
Number.isInteger(10)       // true
Number.isInteger(20)       // true
Number.isInteger(Infinity) // false
```
`Infinity` — это `float`.

Изменения типа значения добавит объекту с структурой `{ title, watched }` новую [форму](https://habr.com/ru/company/otus/blog/446446/#:~:text=doSomething(object.foo)%3B%0A//%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E-,%D0%A4%D0%BE%D1%80%D0%BC%D1%8B,-%D0%92%20%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0%D1%85%20%D0%BD%D0%B0).

<details>
<summary>utils/statistics.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/0ef23aac0abab98a57c24529e784cf0b52089cf5/src/utils/statistics.js#L23
</details>

Функция, которая проверяет `watched` также (скрыто) будет должна учитывать разный тип `watched`; сравнить целое число (`value`) с целым числом `10` не тоже самое, что сравнить с "числом с плавающей точкой". 

Всё это негативно скажется на производительности и возможностях компилятору оптимизировать функцию.

2021-05-22 05:34 UTC, AlexMasterov commented on src/view/stats.js
> +const sortedFilmByGenreCounts = (films) => {
`sorted`FilmByGenreCounts

Б10

2021-05-22 05:37 UTC, El-Leto commented on package.json
> +    "chartjs-plugin-datalabels": "0.7.0"
А вот тут, это не оно?
return new Chart(statisticCtx, {
    plugins: [ChartDataLabels],

2021-05-22 05:47 UTC, AlexMasterov commented on package.json
> +    "chartjs-plugin-datalabels": "0.7.0"
Ты не пользуешься плагином для форматирования вывода. В этом месте потребуется удалить по другому замечанию.

2021-05-22 10:19 UTC, AlexMasterov commented on src/view/stats.js
> +  const rankNam = getRankName(countWatchedFilms(films));
Звание следует вычислять в соответствующем презентере, который сможет его _обновлять_ по подписке на изменения в модели и _хранить_ в актуальном виде. 

Если другим компонентом для их работы требуется знать актуальное звание, то они должны его получать через публичный метод или геттер презентера, который его хранит (а не в обход и дублируя его работу!). Для этого такой презентер им нужно передать в конструктор, в качестве зависимости.

2021-05-22 10:25 UTC, AlexMasterov commented on src/view/stats.js
> +  const minutes = Math.floor(totalWatchedTimeInMin) - (hours * MINUTES_IN_HOUR);
<details>
<summary>getTimeFromMins</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/0ef23aac0abab98a57c24529e784cf0b52089cf5/src/utils/format-date.js#L10-L18
</details>

Функция `getTimeFromMins` делает два действия: вычисляет время и его форматирует. Можно разделит её на две функции и здесь использовать ту, которая только вычисляет время, возвращая объект с `{ hous, minutes }`.

Также добавить возможно изменять форматирования для самой функции  `getTimeFromMins`, например, через доп. параметры:

```js
const getTimeFromMins = (mins, { hours = 'm', minutes = 'm' } = {} ) { ... }
```
Тогда получится её переиспользовать с разным форматированием.

2021-05-23 20:00 UTC, AlexMasterov approved these changes
Для этого задания уже сделано много проверок, а в его PR внесено много кода.

Пожалуйста, обязательные замечания в остатке исправь при выполнении следующего.

2021-05-23 20:00 UTC, merged

2021-05-23 20:05 UTC, AlexMasterov commented on src/view/stats.js
> +  const topGenre = (array) => {
`topGenre`

Б10

> Очередная загадочная функция

2021-05-23 20:09 UTC, AlexMasterov commented on src/utils/statistics.js
> +const WATCHED_TITLES = [
См. внимательно https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/pull/13#discussion_r637350593:
> С учетом изменений нужно учесть критерий Б14

`WATCHED_TITLES`

Б14

Нужно переместить константу (массив) в начало модуля.

2021-05-23 20:14 UTC, AlexMasterov commented on src/view/stats.js
> +
<details>
<summary>view/stats.js</summary>

https://github.com/El-Leto/1489861-cinemaddict-14/blob/b6dce2e8b56bb86fdb0b21d6088201e06194c1c6/src/view/stats.js#L6-L14
</details>

Однажды подобное было сделано исключительно под некомпетентного проверяющего, но с ним потом разобрались. Он же просил создать константы для элементов DOM, которые можно получить только после загрузки самого DOM и это требует побочного эффекта, что никак не может быть константой.

2021-05-23 20:16 UTC, El-Leto commented on src/view/stats.js
> +
Подумала о магических цифрах.
Нашла еще проблему, что при нажатии на контролы Статистика появляется.

2021-05-23 20:17 UTC, AlexMasterov commented on src/view/stats.js
> +          <p class="statistic__item-text">${countWatchedFilms(films)} <span class="statistic__item-description">movies</span></p>
<details>
<summary>view/stats.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/52ebbc0f3540c4a282b9c5ce0c019a110df0e8a8/src/view/stats.js#L103
</details>

`watchedFilms`(films)

<details>
<summary>view/stats.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/52ebbc0f3540c4a282b9c5ce0c019a110df0e8a8/src/view/stats.js#L144
</details>

`countWatchedFilms`(films)

2021-05-23 20:45 UTC, AlexMasterov commented on src/view/stats.js
> +
> Подумала о магических _цифрах_

<details>
<summary>view/stats.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/52ebbc0f3540c4a282b9c5ce0c019a110df0e8a8/src/view/stats.js#L6-L14
</details>

Строго говоря, здесь только _числа_ и _строки_.

А почему только _эти_ строки 😃

Кстати, тот парень из веб-студии предлагал вообще все строки записать, как константы. В нашем чате он показывал пример создания констант для имен селекторов. У меня даже скриншот где-то есть, но стыдно показывать. 

`padding`: TICKS_PADDING,

Что здесь _магического_?

Настоящая проблема "магических значений" в большом скоупе. Также важно помнить, что в JS нет настоящих констант, а все эти "константы" будут использоваться через замыкание, которое имеет свою цену. Код выполняется на стороне браузера пользователя, а для этого его сначала нужно ему передать — от таких "констант" размер неслабо увеличивается, когда наоборот почти ВСЕ пытаются его уменьшить 😄

> Исправлять не нужно

2021-05-23 20:46 UTC, AlexMasterov commented on src/view/stats.js
> +
<details>
<summary>view/stats.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/52ebbc0f3540c4a282b9c5ce0c019a110df0e8a8/src/view/stats.js#L45-L100
</details>

Лучше бы попробовала переиспользовать часть конфига, например этого:

```js
const noDisplay = {display: false};

const scaleAxes = {
  gridLines: noDisplay,
  ticks: {
    beginAtZero: true,
    fontSize: 20,
  },
};
```

2021-05-23 20:55 UTC, AlexMasterov commented on src/presenter/profile.js
> +    if (!this._films.length) {
Отвечая на твой комментарий под другим замечанием упомянул веб-студию (= дно индустрии).

Вот такие проверки (!`this._films.length`) тоже от туда.

2021-05-23 21:34 UTC, El-Leto commented on src/presenter/profile.js
> +    this._films = this._filmsModel.get().slice();
Кажется в этот раз поняла все верно и исправила. И теперь в статистике отображается ранг и фильмы новые сортируются.