Добавит попытки удаления и обновления комментариев
htmlacademy-ecmascript/1489861-cinemaddict-14 pull request #15
Opened 2021-05-26 17:36 UTC by El-Leto

2021-05-28 20:22 UTC, AlexMasterov requested changes

2021-05-28 20:22 UTC, AlexMasterov commented on src/model/comments.js
>        throw new Error('Can\'t delete unexisting item');
```diff
- throw new Error('Can\'t delete unexisting item');
+ throw new Error('Can\'t delete unexisting comment');
```

2021-05-28 20:22 UTC, AlexMasterov commented on src/main.js
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/4d1fd63a0989466bd1a480e4ae8a969ae508c6f5/src/main.js#L31
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/4d1fd63a0989466bd1a480e4ae8a969ae508c6f5/src/main.js#L40
</details>

`empryFilmCount`
`filmsCount`

Это `view`. Нужно назвать по лучше.

2021-05-28 20:22 UTC, AlexMasterov commented on src/const.js
> +const TIMEOUT = 1000;
```diff
- const TIMEOUT = 1000;
+ const SHAKE_TIMEOUT = 1000;
```

2021-05-28 20:22 UTC, AlexMasterov commented on src/view/popup.js
> +            deleteId: deleteId,
ES6+:

```diff
- deleteId: deleteId,
+ deleteId,
```

2021-05-28 20:30 UTC, AlexMasterov requested changes

2021-05-28 20:30 UTC, AlexMasterov commented on src/presenter/popup.js
> +        this._view.showError();
```
Uncaught (in promise) TypeError: this._view.showError is not a function
    at popup.js:83
```
Б2

Вроде this._view.`showError` больше нет.

2021-05-29 07:03 UTC, El-Leto commented on src/main.js
Просто добавить view не очень?

2021-05-29 10:10 UTC, AlexMasterov commented on src/main.js
> Просто добавить view не очень?

Будет достаточно.

`empry`FilmCount

Здесь нужно исправить опечатку.

[`Б 4`](https://up.htmlacademy.ru/ecmascript/14/criteries#b4)
> Для названия значений используются **английские существительные**

2021-05-29 10:20 UTC, AlexMasterov requested changes

2021-05-29 10:20 UTC, AlexMasterov commented on src/const.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/120066508-761e2a00-c07f-11eb-8893-2870ebb0fa06.png)

```
PUT https://14.ecmascript.pages.academy/cinemaddict/movies/0 net::ERR_INTERNET_DISCONNECTED
```

</details>

См. ТЗ:
> **Если запрос не удалось выполнить (сервер недоступен, произошла ошибка)**, форма создания остаётся открытой, к ней применяется эффект «покачивание головой»

Если в отсутствие сети открыть попап и нажимать на кнопки, то нет эффекта "покачивание головой".

Нужно доработать.

2021-05-29 10:20 UTC, AlexMasterov commented on src/const.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/120066614-f3e23580-c07f-11eb-8ec3-35bf5f29081a.png)

</details>

Если в отсутствие сети открыть попап и нажимать на кнопки в карточках, то нет эффекта "покачивание головой".

Нужно доработать.

2021-05-29 10:20 UTC, AlexMasterov commented on src/presenter/films-list.js
> +        this._api.addComment(update.filmId, update.comment)
<details>
<summary>presenter/films-list.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/0fa9ac47a2ef2b243ad472d5956f193f3d7685f9/src/presenter/films-list.js#L264
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/0fa9ac47a2ef2b243ad472d5956f193f3d7685f9/src/presenter/films-list.js#L267
</details>

См. [Promise.p.`finally`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally):
```js
.then()
.catch()
.finally(() => { // завершён (успешно или с ошибкой)
  this._popupPresenter.setDefaultStatus();
});
```

2021-05-29 10:26 UTC, El-Leto commented on src/const.js
А то что весь попап трясется не пойдет?

2021-05-29 10:38 UTC, AlexMasterov commented on src/const.js
> форма создания остаётся

Такая формулировка допускает спекуляции, но она же на защите делает всегда "правым" студента, потому что _непонятно_.

2021-05-29 10:45 UTC, merged