Добавит моковые данные
htmlacademy-ecmascript/1489861-cinemaddict-14 pull request #4
Opened 2021-04-08 10:44 UTC by El-Leto

2021-04-08 18:14 UTC, AlexMasterov requested changes

2021-04-08 18:14 UTC, AlexMasterov commented on src/view/film-details-info.js
>        <table class="film-details__table">
<details>
<summary>view/film-details-info.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/058af46f030f52ecca985fcd1c443229e69826c3/src/view/film-details-info.js#L34-L64
</details>

<details>
<summary>Покажи, как можно переиспользовать разметку</summary>

```js
const createDetailsRowTemplate = (term, cell) => (
  `<tr class="film-details__row">
    <td class="film-details__term">${term}</td>
    <td class="film-details__cell">${cell}</td>
  </tr>`
);
```
```js
// createInfoTemplate
`<table class="film-details__table">
  ${createDetailsRowTemplate(`Director`, director)}
  // ...
</table>`
```
</details>

2021-04-08 18:14 UTC, AlexMasterov commented on src/view/film-details-poster.js
>        <p class="film-details__age">18+</p>
`18+`

Нужно использовать значение из данных.

2021-04-08 18:14 UTC, AlexMasterov commented on src/view/site-navigation.js
> +    `<a href="#${name}" class="main-navigation__item">Watchlist <span class="main-navigation__item-count">${count}</span></a>`
`Watchlist`

Нужно использовать значение из данных (= `name`).

> Также нужно учесть регистр букв

2021-04-08 18:14 UTC, AlexMasterov commented on src/main.js
> +  let renderedFIlmCount = FILM_COUNT_PER_STEP;
```diff
- let renderedFIlmCount = FILM_COUNT_PER_STEP;
+ let renderedFilmCount = FILM_COUNT_PER_STEP;
```

2021-04-08 18:14 UTC, AlexMasterov commented on src/main.js
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/058af46f030f52ecca985fcd1c443229e69826c3/src/main.js#L109-L125
</details>

Повторно предупреждаю, что с появлением классов, подобная сборка "попапа с расширенной информаций о фильме" (и обновления отдельный его частей) может оказаться очень сложной в реализации и поддержке.

> Это требует знаний и опыта, выходящего за рамки интенсивов

2021-04-08 18:20 UTC, AlexMasterov requested changes

2021-04-08 18:20 UTC, AlexMasterov commented on src/main.js
> +
<details>
<summary>view/film-details-table.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/058af46f030f52ecca985fcd1c443229e69826c3/src/view/film-details-table.js#L1-L37
</details>

<details>
<summary>view/film-details-info.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/058af46f030f52ecca985fcd1c443229e69826c3/src/view/film-details-info.js#L34-L64
</details>

Часть модулей с функциями для созданий шаблона дублируется и не используется.

Нужно показать попап с расширенной информацией о фильме, в котором используется данные фильма. Все неиспользуемые функции следует удалить.

> Сейчас сложно проверить шаблон с попап и легко запутаться в функциях для его создания 😟

2021-04-09 04:54 UTC, El-Leto commented on src/main.js
Я могу собрать попап просто в одном файле?

2021-04-09 11:03 UTC, AlexMasterov commented on src/main.js
Пока желательно чтобы далее в модуле `film-details` родился один класс-компонент, который на основе цельного шаблона создаст _один_ DOM-элемент. В случае множества классов с отдельными DOM-элементами на часть общей разметки, будет сложно их связать на уровне DOM и обновлять по отдельности.

Для создания частей самой разметки шаблона можно использовать функции в отдельных модулях, например, создать поддиректорию `film-details` и использовать модульное [проксирование ](https://up.htmlacademy.ru/javascript/22/book/6.3#:~:text=%D0%9F%D1%80%D0%BE%D0%BA%D1%81%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5) через `film-details/index.js`:

```
view/film-details.js
view/film-details/index.js
view/film-details/table.js
view/film-details/button-close.js
view/film-details/comment-list.js
```
> Также можно использовать модули напрямую

2021-04-09 11:12 UTC, AlexMasterov commented on src/main.js
Прежде чем пускаться в такие сложности, следует научиться переиспользовать создание однотипной разметки для шаблона. См. [пример в комментарии.](https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/pull/4#discussion_r609962930) 😃

2021-04-12 13:16 UTC, AlexMasterov requested changes

2021-04-12 13:16 UTC, AlexMasterov commented on src/view/film-card.js
> +import { getTimeFromMins }  from '../mock/utils.js';
Далее при реализации получения данных с сервера директорию `mock` потребуется удалить.

2021-04-12 13:16 UTC, AlexMasterov commented on src/mock/utils.js
> +const getTimeFromMins = (mins) => {
<details>
<summary>getTimeFromMins</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/a492174b859e366e1640235c9c630a2647d4fe70/src/mock/utils.js#L41-L49
</details>

> Если планируешь до конца использовать эту функцию, то следует привести её в соответствие с критериями

`60`

Б31

На защите проекта могут придраться.

<details>
<summary>mock/utils.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/a492174b859e366e1640235c9c630a2647d4fe70/src/mock/utils.js#L44-L48
</details>

`if ... return ... else`

[`Д 12`](https://up.htmlacademy.ru/ecmascript/14/criteries#d12)
> Если при использовании условного оператора в любом случае возвращается значение, альтернативная ветка опускается

> [Не используй `else`](https://www.youtube.com/watch?v=bn10mUjnwEc#t=12m36s), когда это возможно

2021-04-12 13:20 UTC, AlexMasterov commented on src/view/film-details-info.js
> +  } = film;
Не исправлено: `film.comments` содержит объекты с комментариями, а нужно хранить лишь их `id`.

Для комментариев нужно создать отдельную структуру и связывать фильм с комментариями по списку `id` из `film.comments`.

2021-04-12 13:25 UTC, AlexMasterov requested changes

2021-04-12 13:25 UTC, AlexMasterov commented on src/view/film-details/controls.js
> +      <input type="checkbox" ${isFavorite ? 'checked' : ''}class="film-details__control-input visually-hidden" id="favorite" name="favorite">
<details>
<summary>createControlsTemplate</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/a492174b859e366e1640235c9c630a2647d4fe70/src/view/film-details/controls.js#L12
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/a492174b859e366e1640235c9c630a2647d4fe70/src/view/film-details/controls.js#L14
</details>

При значениях `true` создается невалидная разметка. Нужно исправить.

> Посмотри внимательно на проблему с шаблонной строкой 😃

2021-04-12 13:28 UTC, El-Leto commented on src/view/film-card.js
> +  const maxlength = 140;
А у меня там в функции идет maxlength - 1. Я считала, получается ... идет всегда 140 символом

2021-04-12 13:34 UTC, AlexMasterov commented on src/view/film-card.js
> +  const maxlength = 140;
<details>
<summary>view/film-card.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/a492174b859e366e1640235c9c630a2647d4fe70/src/view/film-card.js#L20
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/a492174b859e366e1640235c9c630a2647d4fe70/src/view/film-card.js#L35
</details>

Функция получает значение `maxlength` из параметра.

Для числового значения `140` нужно создать переменную в формате константы и вынести в начало модуля, после `import`. Далее её, вместо `maxlength`, передавай функции при вызове в качестве аргумента.

2021-04-12 13:37 UTC, AlexMasterov commented on src/view/film-card.js
> +  const maxlength = 140;
> Я считала, получается ... идет всегда 140 символом
 
Попробуй проверить:
```js
const dymmyDescription = 'a'.repeat(140);
const descriptionPreview = newDescription(dymmyDescription, 140);

descriptionPreview.length // ?
'…'.length // ?
```

2021-04-12 14:55 UTC, El-Leto commented on src/view/film-details/controls.js
> +    `<section class="film-details__controls">
Очень понравился этот метод! Жалко что видимо глаз не наметан, не сразу вижу, где можно применить.

2021-04-12 15:04 UTC, El-Leto commented on src/view/site-navigation.js
> +export const createSiteNavigationTemplate = (siteNavigationItems) => {
назвала не очень?
Если исправлю site на main будет получше?

2021-04-12 15:12 UTC, El-Leto commented on src/view/film-details/table.js
> +          ${createDetailsRowTemplate('Release Date', date.getDate() + ' ' + month + ' ' + date.getFullYear())}
Саш, не очень поняла. Я ведь наоборот для даты фильма в прошлых исправлениях отказалась от dayjs.

2021-04-13 06:06 UTC, AlexMasterov approved these changes
Для задание сделано вполне достаточно 👍🏻

Мелкие замечания в остатке (в том числе необязательные) постарайся учесть при выполнении следующего. Уже нужно торопиться.

> Про отдельную структуру `comments` и связывание комментариев с фильмом постараюсь еще объяснить в чате. Надеюсь, что тогда получиться доработать до реализации получения данных с сервера

2021-04-13 06:06 UTC, AlexMasterov commented on src/view/main-navigation.js
> +export const createMainNavigationTemplate = (mainNavigationItems) => {
export const create`MainNavigation`Template = (`mainNavigation`Items) => { ... }

В название параметра дублируется название функции, что избыточно.

2021-04-13 06:16 UTC, AlexMasterov commented on src/view/film-details/table.js
> +          ${createDetailsRowTemplate('Release Date', date.getDate() + ' ' + month + ' ' + date.getFullYear())}
См. внимательно прошлое [замечание](https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/pull/4#discussion_r609924576):

> date`Create`

> Нужно [из название свойства] убрать глагол. (см. Б4)

> Вместо объекта `dayjs` желательно использовать стандартный объект [`Date`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Date), а `dayjs` использовать для сложной логике со временем и форматирования в шаблонах

<details>
<summary>Покажи что ожидалось</summary>

Ожидание по форматированию:
```diff
- ${createDetailsRowTemplate('Release Date', date.getDate() + ' ' + month + ' ' + date.getFullYear())}
+ ${createDetailsRowTemplate('Release Date', formatReleaseDate(date))}
```

Кроме этого, авторы курса еще на первом JS1 рекомендовали использовать утилитарные функции в модулях проекта через интерфейсы функций, чтобы было проще их заменять:
```js
// utils/date.js
export const formatReleaseDate = (date) => dayjs(date).format('D MMMM YYYY');
```
</details>

2021-04-13 06:22 UTC, AlexMasterov commented on src/view/site-navigation.js
> +export const createSiteNavigationTemplate = (siteNavigationItems) => {
В название параметра функции дублируется название самой функции: `siteNavigation`, что избыточно.

Достаточно: `items`.

2021-04-13 06:22 UTC, merged