Module3 task1
htmlacademy-ecmascript/1489861-cinemaddict-14 pull request #5
Opened 2021-04-15 06:03 UTC by El-Leto

2021-04-15 08:50 UTC, AlexMasterov requested changes

2021-04-15 08:50 UTC, AlexMasterov commented on src/utils.js
> +const createElement = (template) => {
<details>
<summary>createElement</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/400bb9045776e0754f42f70835012917cfc8ae92/src/utils.js#L17-L21
</details>

`//`

Нужно убрать комментарии.

2021-04-15 08:50 UTC, AlexMasterov commented on src/utils.js
> +  const newElement = document.createElement('div'); // 1
new`Element`

Д6

На защите проекта могут придраться.

Желательно изменить название, например на такое:
```diff
- const newElement = document.createElement('div');
+ const wrapper = document.createElement('div');
```

2021-04-15 08:50 UTC, AlexMasterov commented on src/main.js
> +  const popupElement = new PopupView(films).getElement();
filmCard`Element`
popup`Element`

[`Д 6`](https://up.htmlacademy.ru/ecmascript/14/criteries#d6)
> если есть переменные, которые хранят DOM-элемент и содержат слово `Element`, **то это правило работает везде**

Повторно советую не использовать `Element`.

2021-04-15 08:50 UTC, AlexMasterov commented on src/main.js
> +    popupElement.querySelector('.film-details__close-btn').addEventListener('click', () =>{
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/114839371-5b009f00-9dde-11eb-8cfc-7ee9ec9be1c2.png)

</details>

Обработчики накапливаются на кнопках закрытия каждого элемента карточки.

[`Б 36`](https://up.htmlacademy.ru/ecmascript/14/criteries#b36)
> Обработчики события добавляются и удаляются своевременно

Элементы компонентов карточки также не удаляются после закрытия.

2021-04-15 08:50 UTC, AlexMasterov commented on src/main.js
> +  filmCardElement.querySelector('.film-card__comments').addEventListener('click', showPopup);
**3x** .`film-card`__* + `click` !== `showPopup`

[`Д 4`](https://up.htmlacademy.ru/ecmascript/14/criteries#d4)
> Из названия обработчика события и функции-колбэка следует, что это за обработчик

Нужно выбрать формат именования обработчиков событий DOM и придерживаться его во всем проекте.

2021-04-15 08:50 UTC, AlexMasterov commented on src/main.js
> +const body = document.querySelector('body');
Элемент `body` также доступен через свойство `document.body`.

2021-04-15 08:50 UTC, AlexMasterov commented on src/main.js
> +      showMoreButton.getElement().remove();
```js
showMoreButton._element === null           // false
showMoreButton._element instanceof Element // true
```
Элемент кнопки удален из DOM (браузера), но ссылка на него остается в памяти движка.

2021-04-15 08:50 UTC, AlexMasterov commented on src/utils/data.js
> +export { formatReleaseDate, getTimeFromMins };
```diff
- utils/data.js
+ utils/date.js
```

2021-04-15 08:50 UTC, AlexMasterov commented on src/view/film-details.js
> +export default class Popup {
view/`film-details`.js !== `Popup`

[`Б 27`](https://up.htmlacademy.ru/ecmascript/14/criteries#b27)
> Имя модуля должно соответствовать его содержимому

> Например, если в модуле лежит класс `GameView`, то и имя модуля должно быть `game-view`.js

2021-04-15 08:50 UTC, AlexMasterov commented on src/view/film-details/comment-list.js
> +  `<input class="film-details__emoji-item visually-hidden" name="comment-emoji" type="radio" id="emoji-${emoji}" value="${emoji}">
Нет возможности задать атрибут `checked` для `input`.

Нужно доработать.

2021-04-16 07:11 UTC, AlexMasterov requested changes

2021-04-16 07:11 UTC, AlexMasterov commented on src/main.js
> +  onFilmCardClick();
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/416c54b1c72e467316062b1c624845c47f61adc9/src/main.js#L49
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/416c54b1c72e467316062b1c624845c47f61adc9/src/main.js#L55
</details>

[`Б 10`](https://up.htmlacademy.ru/ecmascript/14/criteries#b10)
> Название функции или метода содержит глагол

Функции, которые названы в формате обработчика событий DOM, следует использовать только в качестве коллбэков для метода `.addEventListener` и вызывать в коде как обычные функции — это нарушает критерий именования обычный функции.

> Для обработчиков событий самих компонентов будет использоваться именование с `handle*`, чтобы учесть этот критерий. Прошу иметь ввиду и далее стараться не путать

2021-04-16 07:11 UTC, AlexMasterov commented on src/main.js
> +    filmCard.querySelector('.film-card__comments').addEventListener('click', showPopup);
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/416c54b1c72e467316062b1c624845c47f61adc9/src/main.js#L50-L52
</details>

.`film-card`__comments + `click` !== `showPopup`
.`film-card`__title + `click` !== `showPopup`
.`film-card`__comments + `click` !== `showPopup`

[`Д 4`](https://up.htmlacademy.ru/ecmascript/14/criteries#d4)
> Название обработчика строится следующим образом:

> `on` + `(на каком элементе)` + что случилось

**или** (для всего проекта!)

> `(на каком элементе)` + `что случилось` + `Handler`

Название обработчика события DOM (для `.addEventListener`) не соответствует не одному из этих двух вариантах. 

Нужно выбрать один вариант именования обработчиков и придерживаться его во всем проекте. В имение обработчика нужно _точно_ и _полностью_ повторить названия элемента. (в общем случае можно использовать только общие название `filmCard`).

Это критерий с JS1, который хорошо объясняют на лайв-лекции. В чем проблема? :worried: 

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/416c54b1c72e467316062b1c624845c47f61adc9/src/main.js#L49

Таким образом (=` onFilmCardClick`) долен называться сам обработчик для трех элементов `filmCard`, в котором вызвана обычная функция `showPopup` 😃

2021-04-16 08:02 UTC, El-Leto commented on src/main.js
> +    filmCard.querySelector('.film-card__comments').addEventListener('click', showPopup);
С обработчиками действительно проблема. Поищу сегодня еще какие-нибудь видео о них. Как их просто вызвать я понимаю, а вот когда их нужно вовремя снять и вот эти моменты с наименованием - тут все как в тумане.

2021-04-16 08:20 UTC, El-Leto commented on src/main.js
> +    filmCard.querySelector('.film-card__comments').addEventListener('click', showPopup);
Если я тебя верно поняла, то исправила вот так. Но вопрос: а я не могу саму функцию showPopup просто переименовать на onFilmCardClick.

2021-04-16 08:20 UTC, El-Leto commented on src/view/film-details/comment-list.js
> +  `<input class="film-details__emoji-item visually-hidden" name="comment-emoji" type="radio" id="emoji-${emoji}" value="${emoji}">
Саш, вот тут тоже можешь что-нибудь еще пояснить. Не совсем поняла, что нужно сделать.

2021-04-16 08:21 UTC, AlexMasterov commented on src/main.js
> +    filmCard.querySelector('.film-card__comments').addEventListener('click', showPopup);
> Но вопрос: а я не могу саму функцию showPopup просто переименовать на onFilmCardClick

Да, можешь.

2021-04-16 08:25 UTC, AlexMasterov commented on src/view/film-details/comment-list.js
> +  `<input class="film-details__emoji-item visually-hidden" name="comment-emoji" type="radio" id="emoji-${emoji}" value="${emoji}">
<details>
<summary>markup\popup-add-comment.html</summary>

![image](https://user-images.githubusercontent.com/700213/114995049-1809fe80-9ea6-11eb-8c0a-f72fd5f60593.png)
![image](https://user-images.githubusercontent.com/700213/114995153-3243dc80-9ea6-11eb-93ee-c5147021426c.png)

</details>

Как будет реализован (пере)рендер выбор эмоджи для комментария?

Сейчас шаблон не предусматривает установку атрибута `checked` 😃

2021-04-16 08:31 UTC, AlexMasterov commented on src/view/film-details/comment-list.js
> +  `<input class="film-details__emoji-item visually-hidden" name="comment-emoji" type="radio" id="emoji-${emoji}" value="${emoji}">
Пока это отложи.

2021-04-16 10:15 UTC, AlexMasterov commented
👍🏻

2021-04-16 10:16 UTC, merged