Module5 task1
htmlacademy-ecmascript/1489861-cinemaddict-14 pull request #8
Opened 2021-04-22 19:36 UTC by El-Leto

2021-04-24 18:21 UTC, El-Leto commented
Саша, если добавлять фильмы в просмотренные, фавориты и вотчлист из попапа, то мой датабилдинг не работает. Очень нужна твоя помощь.

2021-04-24 18:31 UTC, AlexMasterov requested changes

2021-04-24 18:31 UTC, AlexMasterov commented on src/presenter/film-card.js
> +      replace(this._filmComponent, prevFilmCardComponent);
> Саша, если добавлять фильмы в просмотренные, фавориты и вотчлист из попапа, то мой датабилдинг не работает. Очень нужна твоя помощь

<details>
<summary>presenter/film-card.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/film-card.js#L55
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/film-card.js#L59
</details>

```js
this._filmComponent // undefined
```

```diff
- replace(this._filmComponent, prevFilmCardComponent);
+ replace(this._filmCardComponent, prevFilmCardComponent); 
```

2021-04-24 18:38 UTC, AlexMasterov requested changes

2021-04-24 18:38 UTC, AlexMasterov commented on src/presenter/films-list.js
> +export default class FilmList {
<details>
<summary>presenter/films-list.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/films-list.js#L17-L18

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/films-list.js#L92
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/films-list.js#L100
</details>

<details>
<summary>presenter/films-list.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/films-list.js#L84
</details>

Д3

2021-04-24 18:38 UTC, AlexMasterov commented on src/presenter/films-list.js
> +      this._showMoreButtonComponent.removeElement();
<details>
<summary>presenter/films-list.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/films-list.js#L73-L74
</details>

<details>
<summary>presenter/film-card.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/film-card.js#L63-L64
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/film-card.js#L66-L67
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/film-card.js#L71-L72
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/film-card.js#L102-L103
</details>

и т.п.

Используй здесь и в похожим местах **во всем проекте** [функцию `remove` из демо проекта](https://github.com/htmlacademy-ecmascript/taskmanager-14/blob/module-5/src/utils/render.js#L59-L66).

2021-04-24 18:38 UTC, AlexMasterov commented on src/presenter/film-card.js
> +export default class FilmCard {
<details>
<summary>presenter/film-card.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/film-card.js#L11-L12
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/film-card.js#L16
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/film-card.js#L81
</details>

Д3

2021-04-24 18:44 UTC, AlexMasterov requested changes

2021-04-24 18:44 UTC, AlexMasterov commented on src/presenter/film-card.js
> +    const buttonClose = document.querySelector('.film-details__close-btn');
<details>
<summary>presenter/film-card.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/film-card.js#L87-L91
</details>

[`Д 26`](https://up.htmlacademy.ru/ecmascript/14/criteries#d26)
> Операции над DOM-элементами инкапсулированы

Нужно у `view` реализовать метод для добавления обработчика:

```js
this._popupComponent.addCloseButtonClickHandler(handlePopupCloseButtonClick);
```

2021-04-24 18:44 UTC, AlexMasterov commented on src/presenter/film-card.js
> +  _buttonEscKeydownHandler(evt) {
[`Д 8`](https://up.htmlacademy.ru/ecmascript/14/criteries#d8)
> Методы внутри классов упорядочены

Нужно переместить метод обработчика _событий DOM_ в самый низ класса.

2021-04-24 18:48 UTC, AlexMasterov requested changes

2021-04-24 18:48 UTC, AlexMasterov commented on src/utils/common.js
> +const updateItem = (items, update) => {
<details>
<summary>updateItem</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/utils/common.js#L11
</details>

```diff
- const updateItem = (items, update) => {
+ const updateItemById = (items, update) => {
```

2021-04-24 18:48 UTC, AlexMasterov commented on src/render.js
> +
Желательно перенести модуль в директорию `utils`:

```diff
- src/render.js
+ src/utils/render.js
```

2021-04-24 18:48 UTC, AlexMasterov commented on src/render.js
> +  if (parent === null || oldChild === null || newChild === null) {
<details>
<summary>replace</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/render.js#L37-L47
</details>

Обращение к свойству `oldChild`.`parentElement` происходит _до_ проверки самого `oldChild` на `null`.

<details>
<summary>Покажи пример проблемы</summary>

```js
replace(null, null);
```
```
render.js:54 Uncaught TypeError: Cannot read property 'parentElement' of null
```
</details>

[`Б 2`](https://up.htmlacademy.ru/ecmascript/14/criteries#b2)
> При выполнении кода не возникает _необработанных_ ошибок

2021-04-24 18:48 UTC, AlexMasterov commented on src/render.js
> +import Abstract from './view/abstract.js';
./`view`/`abstract`.js

```diff
- import Abstract from './view/abstract.js';
+ import AbstractView from './view/abstract.js';
```

2021-04-24 19:10 UTC, AlexMasterov requested changes

2021-04-24 19:10 UTC, AlexMasterov commented on src/view/film-card.js
<details>
<summary>view/film-card.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/view/film-card.js#L71
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/view/film-card.js#L76
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/view/film-card.js#L81
</details>

Методы для установки трех _разных_ обработчиков записывают значение `callback` в одно и тоже свойство `this._callback.click`, что ведет к перезаписи.

~Б24

> Не важно, что им сейчас где-то снаружи всем добавляется один обработчик

Нужно использовать разные свойства.

2021-04-24 19:10 UTC, AlexMasterov commented on src/view/film-card.js
<details>
<summary>view/film-card.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/view/film-card.js#L86
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/view/film-card.js#L91
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/view/film-card.js#L96
</details>

<details>
<summary>view/film-card.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/view/film-card.js#L117
</details>

[`Б 10`](https://up.htmlacademy.ru/ecmascript/14/criteries#b10)
> Название метода должно быть глаголом и соответствовать действию, которое выполняет метод

Нужно в название всех подобных методов поставить `click` _в начало_:

 
```diff
- this._callback.watchlistClick = callback; 
+ this._callback.clickWatchlist = callback; 
```

2021-04-24 19:10 UTC, AlexMasterov commented on src/view/film-card.js
> +    this.getElement().querySelector('.film-card__controls-item--add-to-watchlist').addEventListener('click', this._watchlistClickHandler);
.film-card__controls-item--`add-to-watchlist` + `click` !== this._`watchlist`ClickHandler

Д4

2021-04-24 19:10 UTC, AlexMasterov commented on src/view/film-card.js
> +    this.getElement().querySelector('.film-card__controls-item--mark-as-watched').addEventListener('click', this._watchedClickHandler);
.film-card__controls-item--`mark-as-watched` + `click` !== this._`watched`ClickHandler

Д4

2021-04-24 19:10 UTC, AlexMasterov commented on src/view/popup.js
> +
<details>
<summary>view/popup.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/view/popup.js#L43
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/view/popup.js#L48
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/view/popup.js#L53
</details>

this._callback.watchlist`Change` и т.п.

Б10

2021-04-24 19:18 UTC, AlexMasterov requested changes

2021-04-24 19:18 UTC, AlexMasterov commented on src/presenter/film-card.js
> +      replace(this._filmComponent, prevFilmCardComponent);
<details>
<summary>presenter/film-card.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/film-card.js#L54-L56
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/film-card.js#L58-L59
</details>

Почему действия в условиях дублируются 🤔

[`Д 11`](https://up.htmlacademy.ru/ecmascript/14/criteries#d11)
> Отсутствует дублирование кода

Нужно здесь разобраться с логикой и убрать лишние или переделать.

2021-04-24 19:18 UTC, AlexMasterov commented on src/view/popup.js
> +
См. задание:
> **Обратите внимание**, что **изменение информации о фильме в попапе** — клики по кнопкам «Add to watchlist», «Already watched», «Add to favorites» — **должно отображаться в списке фильмов мгновенно**. При изменении информации и обновлении списка фильмов попап не должен закрываться самовольно

<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/115970412-da167580-a54a-11eb-8a81-79d26e4694a4.png)

</details>

Нужно разобраться и доработать.

2021-04-24 19:19 UTC, AlexMasterov commented on src/presenter/film-card.js
> +    this._popupComponent.setWatchedChangeHandler(this._handleWatchedClick);
<details>
<summary>presenter/film-card.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/film-card.js#L45-L47
</details>

this._popupComponent.setWatchlist`Change`Handler(this._handleWatchlist`Click`) 🤔

Не единообразно. На защите проекта могут придраться.

Желательно исправить.

2021-04-24 19:23 UTC, AlexMasterov requested changes

2021-04-24 19:23 UTC, AlexMasterov commented on src/presenter/films-list.js
> +    this._renderedFIlmCount = FILM_COUNT_PER_STEP;
this._renderedF`I`lmCount

Б3

См. также https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/pull/4#discussion_r609968187

2021-04-24 19:36 UTC, AlexMasterov requested changes

2021-04-24 19:36 UTC, AlexMasterov commented on src/presenter/films-list.js
> +//import PopupView from '../view/popup.js';
<details>
<summary>presenter/films-list.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/films-list.js#L6
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/7c70773fd1683b2a4f2c01ad1e48d8b037e7448d/src/presenter/films-list.js#L8
</details>

`//`

Б18

2021-04-26 12:10 UTC, AlexMasterov requested changes
К сожалению, нужно немного доработать.

2021-04-26 12:10 UTC, AlexMasterov commented on src/view/popup.js
> +    this.getElement().querySelector('.film-details__control-label--watchlist').addEventListener('change', this._addToWatchlistChangeHandler);
У элемента `.film-details__control-label--watchlist` нет события `change`. Поэтому в попап обработчики на кнопки не работают и перерисовки её карточки в списке не происходит.

Нужно исправить.

См. также другое [актуальное замечание](https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/pull/8#discussion_r619698048).

2021-04-26 12:11 UTC, AlexMasterov commented on src/view/popup.js
> +
Замечание актуально.

2021-04-26 12:15 UTC, AlexMasterov requested changes

2021-04-26 12:15 UTC, AlexMasterov commented on src/presenter/films-list.js
> +    this._renderFilmsList();
[Прошлое замечание](https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/pull/8#discussion_r619695468) закрыто, но не исправлено.

Всё больше замечаний закрываются, но по факту не исправляются, а некоторые типовые повторяются по много раз 😟

2021-04-26 12:28 UTC, AlexMasterov commented on src/presenter/films-list.js
> +    this._noFilmsView = new NoFilmsView();
<details>
<summary>presenter/films-list.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/34b1032dd1d584bf8e79900b39118bd24ffc8a48/src/presenter/films-list.js#L85-L88
https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/34b1032dd1d584bf8e79900b39118bd24ffc8a48/src/presenter/films-list.js#L56-L58
</details>

`NoFilmsView` используется только в отсутствие фильмов, но его компонент создается заранее и занимает памятью

2021-04-26 13:51 UTC, El-Leto commented on src/view/popup.js
> +    this.getElement().querySelector('.film-details__control-label--watchlist').addEventListener('change', this._addToWatchlistChangeHandler);
Исправила на this._watchlistChangeHandler

2021-04-26 13:52 UTC, El-Leto commented on src/view/popup.js
> +    this.getElement().querySelector('.film-details__control-label--watched').addEventListener('change', this._markAsWatchedChangeHandler);
Исправила на this._watchedChangeHandler

2021-04-26 13:53 UTC, El-Leto commented on src/presenter/films-list.js
> +  _renderFilmsList() {
Исправила на _renderAllFilms, так будет получше?

2021-04-26 13:58 UTC, AlexMasterov commented on src/presenter/films-list.js
> +  _renderFilmsList() {
> Исправила на _renderAllFilms, так будет получше?

Да

2021-04-26 14:11 UTC, AlexMasterov commented on src/view/popup.js
> +    this.getElement().querySelector('.film-details__control-label--watchlist').addEventListener('change', this._addToWatchlistChangeHandler);
> Исправила на this._watchlistChangeHandler

Предвижу, что по другому замечанию потребуется исправить сам тип события: this._watchlist`Change`Handler. Не понимаю, как это мог пропустить на прошлой проверке — это еще одна, но более глубокая, причина нерабочих кнопок попапа 😃

2021-04-26 14:20 UTC, El-Leto commented on src/presenter/film-card.js
> +    document.body.appendChild(this._popupView.getElement());
Исправила на render(document.body, this._popupView, InsertPosition.BEFORE_END);

2021-04-26 14:20 UTC, El-Leto commented on src/presenter/film-card.js
> +    document.body.appendChild(this._popupView.getElement());
Пишу, что самой проверять, что закрыла этот пункт.

2021-04-26 14:27 UTC, AlexMasterov commented on src/presenter/film-card.js
> +    document.body.appendChild(this._popupView.getElement());
> Пишу, что самой проверять, что закрыла этот пункт.

Такие комментарии напрасно триггерят оповещение на почту.
Вместо этого, пожалуйста, лучше на мои замечания добавляй эмоцию глаза 👀 или другую, на выбор.

2021-04-26 14:29 UTC, AlexMasterov commented on src/presenter/film-card.js
> +    document.body.appendChild(this._popupView.getElement());
> Исправила на render(document.body, this._popupView, InsertPosition.BEFORE_END);

`InsertPosition.BEFORE_END` — наиболее используемое место для вставки.

<details>
<summary>utils/render.js</summary>

https://github.com/htmlacademy-ecmascript/1489861-cinemaddict-14/blob/34b1032dd1d584bf8e79900b39118bd24ffc8a48/src/utils/render.js#L8
</details>

В таком случае можно сделать его местом _по умолчанию_:
```diff
- const render = (container, element, place) => { 
+ const render = (container, element, place = InsertPosition.BEFORE_END) => { 
```

2021-04-27 17:40 UTC, AlexMasterov commented
[LGTM](https://coub.com/view/29wef6)!

2021-04-27 17:40 UTC, merged